import {Providers} from "./providers";
import './globals.css'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import {Box, Center, Flex, Spacer} from "@chakra-ui/react";
import SideNav from "@/components/SideNav";
import {Header} from "@/components/header";
import Script from 'next/script'
import React from "react";


const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <head><title>Alky&apos;s Place</title></head>
        <body className={inter.className}>
        <Providers>
            <Center>
                <Box
                    data-component='Top Box'
                    width={{
                        base: '100%',
                        mobile: '400px',
                        sm: '600px',
                        md: '750px'
                    }}>
                    <Header/>
                    <Flex
                        width={'100%'}
                        justifyContent={{
                            base: 'center',
                            sm: 'left'
                        }}>
                        <Box display={{
                            base: 'none',
                            sm: 'block'
                        }}>
                            <SideNav/>
                        </Box>
                        <Box m={{
                            base: '0 10px',
                            sm: '0 0 0 10px'
                        }}
                        width={'100%'}>
                            {children}
                        </Box>
                    </Flex>
                </Box>
            </Center>
        </Providers>
        </body>
        <Script
            src="https://product-gallery.cloudinary.com/all.js"
            type="text/javascript"
        />
        </html>
    )
}
