import {Providers} from "./providers";
import './globals.css'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import {Box, Center, Flex, Spacer} from "@chakra-ui/react";
import SideNav from "@/components/SideNav";
import {Header} from "@/components/header";


const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <Providers>
            <Center>
                <Box>
                    <Header width={'750px'}/>
                    <Flex
                        width={'750px'}>
                        <SideNav/>
                        <Spacer/>
                        <Box w={'610px'}>
                            {children}
                        </Box>
                    </Flex>
                </Box>
            </Center>
        </Providers>
        </body>
        </html>
    )
}
